const service = (title, short, description, features, cta) => ({ title, short, description, features, cta });
const module = (title, intro, features, benefit, related) => ({ title, intro, features, benefit, related });
export default {
  dir: 'ltr', language: 'العربية', home: 'Home', about: 'About', services: 'Services', modules: 'ERPNext Modules', contact: 'Contact', consultation: 'Book a Consultation',
  nav: { menu: 'Open menu', close: 'Close menu' },
  hero: { eyebrow: 'ERPNext consulting for growing businesses', title: 'ERPNext Solutions Built Around Your Business', text: 'I help businesses analyze their needs, implement ERPNext, customize workflows, integrate external platforms, and train users for successful adoption.', primary: 'Start Your Project', secondary: 'Explore Services', core: 'ERPNext Core' },
  labels: { learn: 'Learn More', allModules: 'View All Modules', viewModule: 'View Module', features: 'Key features', benefits: 'Business value', related: 'Related modules', considerations: 'Implementation considerations', process: 'How I work on an ERPNext project', readMore: 'Explore service', backTop: 'Back to top', breadcrumb: 'Breadcrumb', required: 'Required field' },
  home: { servicesTitle: 'Integrated ERPNext Services', servicesText: 'From business analysis and solution design to implementation, development, integration, training, and support—every phase is shaped around how your company works.', modulesTitle: 'ERPNext Modules', modulesText: 'Configure a broad range of ERPNext modules to cover the core administrative and operational processes in your organization.', whyTitle: 'Why work with Mohamed Sayed?', clientsTitle: 'Trusted by businesses across operations', clientsText: 'Supporting practical ERP and technology work for businesses in food, engineering, and professional services.', processTitle: 'A clear path from requirements to adoption', ctaTitle: 'Planning to implement ERPNext?', ctaText: "Let’s discuss your business needs and build the right ERP solution for your organization.", cta: 'Request a Consultation' },
  why: [ ['Business first', 'Every project begins with your operating model, challenges, and outcomes—not with a default system setup.'], ['ERPNext expertise', 'A focused practice around implementing, extending, and tailoring ERPNext.'], ['Custom solutions', 'Workflows and features are designed for your requirements, not forced into a one-size-fits-all template.'], ['End-to-end support', 'Guidance from analysis and delivery through training, go-live, and continuous improvement.'], ['Integration mindset', 'Connect ERPNext to the platforms and services that already power your business.'], ['User adoption', 'Success means people can use the system confidently and consistently.'] ],
  process: [ ['01', 'Discovery', 'Understand the business, its goals, and its current friction points.'], ['02', 'Business Analysis', 'Map processes and workflows, then identify practical requirements.'], ['03', 'Solution Design', 'Select modules, customizations, and integrations for the right solution.'], ['04', 'Implementation', 'Configure ERPNext, set up operations, and migrate data when needed.'], ['05', 'Training & Go-Live', 'Prepare users and support the transition to live operation.'], ['06', 'Support & Optimization', 'Solve issues and improve processes as your business evolves.'] ],
  aboutPage: { title: 'Mohamed Sayed — ERP Consultant', lead: 'Practical ERPNext solutions that make everyday operations easier to run and easier to trust.', paragraphs: ['I am Mohamed Sayed, an ERP Consultant specializing in ERPNext. I help companies understand their needs and turn daily operations into structured, scalable ERP solutions.', 'My work covers business analysis and requirements discovery, implementation, customization, external integrations, user training, and post-go-live support.', 'The goal is never simply to install an ERP. It is to build a solution that improves processes, organizes data, reduces manual work, and gives decision-makers clearer visibility.'] },
  servicesPage: { title: 'ERPNext Services', text: 'A complete set of services to implement ERPNext, extend it, and connect it to your current business environment.' },
  modulesPage: { title: 'ERPNext Modules', text: 'Explore key ERPNext modules that can be configured and customized for the different operations in your organization.' },
  servicesData: {
    'erpnext-implementation': service('ERPNext Implementation', 'Set up ERPNext around the real operations of your company.', 'ERPNext implementation is not simply installing a system. It begins with understanding your business and current processes, then designing and configuring ERPNext to serve the organization. I translate operating requirements into clear workflows, roles, master data, and practical day-to-day processes.', ['Business process analysis', 'ERPNext setup', 'Module configuration', 'User & role management', 'Workflow configuration', 'Master data setup', 'Customization', 'Data migration', 'Testing', 'User training', 'Go-live support'], 'Discuss Your ERPNext Project'),
    'erpnext-development': service('ERPNext Development & Customization', 'Extend ERPNext where standard functionality does not fit your process.', 'When standard ERPNext capabilities do not fully cover a business requirement, tailored development can provide the right fit without losing maintainability or room to grow.', ['Custom features', 'Custom fields', 'Custom DocTypes', 'Custom scripts', 'Server scripts', 'Workflows', 'Reports & dashboards', 'Print formats', 'Business logic', 'Automation', 'UI customization'], 'Discuss a Custom Requirement'),
    'erpnext-integration': service('ERPNext Integration', 'Connect ERPNext to the platforms that keep your business moving.', 'Integrating ERPNext with external systems removes duplicate data entry and makes information move reliably across your business. Integrations are designed with APIs and the most appropriate connection method for each platform.', ['Payment gateways', 'E-commerce platforms', 'CRM systems', 'Accounting systems', 'Shipping platforms', 'Government platforms', 'External APIs', 'Mobile applications', 'Custom software'], 'Plan an Integration'),
    'business-analysis': service('Business Analysis for ERP', 'Turn how the business works into clear, implementable system requirements.', 'Before implementing ERPNext, it is essential to understand how the organization actually works. I review current processes, pain points, user needs, and the requirements the system should support.', ['Understand current processes', 'Identify pain points', 'Gather requirements', 'Map workflows', 'Identify automation opportunities', 'Define ERP requirements', 'Recommend solution'], 'Analyze Your Business'),
    training: service('ERPNext User Training', 'Role-based practical training that helps teams adopt the system.', 'ERPNext succeeds when users can use it correctly and confidently. Training is prepared around user roles and the modules people use in their daily work, delivered online or on-site depending on the project.', ['System navigation', 'User roles', 'Accounting', 'Buying & selling', 'Stock & manufacturing', 'HR & projects', 'Reports', 'Daily workflows'], 'Request Training'),
    support: service('ERPNext Support & Optimization', 'Keep ERPNext stable, useful, and aligned with changing needs.', 'Once ERPNext is live, operational questions and new requirements naturally emerge. Ongoing support helps stabilize the system and improve how it is used as your business develops.', ['Troubleshooting', 'Bug investigation', 'Configuration support', 'User assistance', 'Performance review', 'Workflow improvements', 'Reports', 'Customization support', 'System optimization'], 'Get ERPNext Support')
  },
  modulesData: {
    accounting: module('ERPNext Accounting', 'Manage finance, accounting operations, and financial reporting through one connected system.', ['Chart of accounts', 'General ledger', 'Accounts payable & receivable', 'Sales & purchase invoices', 'Payments & taxes', 'Financial reports', 'Cost centers', 'Multi-company'], 'Unify financial data and connect it directly with selling, buying, stock, and assets.', ['selling','buying','stock','assets']),
    buying: module('ERPNext Buying', 'Manage the purchasing cycle from material request to receiving products and supplier invoices.', ['Material requests', 'Supplier management', 'RFQs', 'Purchase orders', 'Purchase receipts', 'Purchase invoices', 'Supplier pricing'], 'Organize purchasing, improve supplier follow-up, and reduce manual errors.', ['stock','accounting','manufacturing']),
    selling: module('ERPNext Selling', 'Manage the sales cycle from lead and customer to quotation, order, delivery, and invoice.', ['Customers & leads', 'Quotations', 'Sales orders', 'Delivery notes', 'Sales invoices', 'Pricing', 'Sales reports'], 'Connect sales with inventory and accounting for a clearer sales cycle.', ['stock','accounting','project-management']),
    stock: module('ERPNext Stock & Inventory', 'Manage inventory, warehouses, and item movements in one central view.', ['Warehouses', 'Items', 'Stock entries', 'Stock reconciliation', 'Serial numbers', 'Batch tracking', 'Transfers', 'Inventory reports'], 'Maintain accurate visibility into stock levels and movement across warehouses.', ['buying','selling','manufacturing']),
    assets: module('ERPNext Assets', 'Manage fixed assets throughout their complete lifecycle.', ['Asset creation', 'Asset purchase', 'Asset movement', 'Depreciation', 'Asset maintenance', 'Asset disposal', 'Asset reports'], 'Keep asset data, movements, and depreciation visible and connected to finance.', ['accounting','stock','project-management']),
    manufacturing: module('ERPNext Manufacturing', 'Manage production operations while connecting inventory, purchasing, and costs.', ['Bill of materials', 'Workstations', 'Operations', 'Work orders', 'Job cards', 'Production planning', 'Material consumption', 'Finished goods', 'Manufacturing reports'], 'Improve planning and trace the journey from raw materials to finished products.', ['stock','buying','accounting']),
    hr: module('ERPNext HR', 'Manage employee data and the processes that support your people.', ['Employee management', 'Departments', 'Leave management', 'Attendance', 'Payroll', 'Recruitment', 'Employee lifecycle', 'HR reports'], 'Create a clearer, more consistent foundation for people operations.', ['accounting','project-management','assets']),
    healthcare: module('ERPNext Healthcare', 'Support core operating processes for healthcare organizations with ERPNext.', ['Patient management', 'Healthcare practitioners', 'Appointments', 'Patient history', 'Medical records', 'Healthcare services', 'Billing integration'], 'The application is configured around the facility’s requirements and operating model.', ['accounting','stock','hr']),
    subcontracting: module('ERPNext Subcontracting', 'Manage manufacturing or service work carried out by suppliers and third parties.', ['Subcontracting orders', 'Supplier management', 'Raw material transfer', 'Subcontracting receipts', 'Consumption tracking', 'Purchase integration'], 'Keep third-party production visible alongside purchasing and inventory.', ['buying','stock','manufacturing']),
    'project-management': module('ERPNext Project Management', 'Manage projects, tasks, resources, costs, and work progress.', ['Projects', 'Tasks', 'Timesheets', 'Project costs', 'Milestones', 'Project billing', 'Progress tracking', 'Project reports'], 'Bring delivery, cost, time, and progress information into a single view.', ['selling','hr','accounting'])
  },
  contactPage: { title: "Let's Talk About Your ERP Project", text: 'Tell me a little about your business and ERPNext requirements. I will get back to you as soon as possible.', fields: ['Name', 'Company', 'Email', 'Phone / WhatsApp', 'Service', 'ERPNext Modules', 'Project Description', 'Preferred Contact Method'], send: 'Send Request', success: 'Thank you. Your request has been received. I will get back to you as soon as possible.' },
  globalCta: { title: 'Have an ERPNext project in mind?', text: "Let's turn your business requirements into a practical ERP solution.", button: 'Start a Conversation' },
  footer: { role: 'ERP Consultant', description: 'ERPNext Implementation · Development · Integration · Business Analysis · Training · Support', rights: '© 2026 Mohamed Sayed. All rights reserved.', social: 'Connect' },
  notFound: { title: "Oops! This page doesn't exist.", text: 'The page you are looking for may have moved or no longer exists.', home: 'Back Home' }
};
